export const countryCodes = [
  { name: 'Afghanistan', code: '93', prefix: '93', numberLength: 10 },
  { name: 'Albania', code: '355', prefix: '355', numberLength: 10 },
  { name: 'Algeria', code: '213', prefix: '213', numberLength: 11 },
  { name: 'Andorra', code: '376', prefix: '376', numberLength: 8 },
  { name: 'Angola', code: '244', prefix: '244', numberLength: 9 },
  { name: 'Antigua and Barbuda', code: '1', prefix: '1', numberLength: 10 },
  { name: 'Argentina', code: '54', prefix: '54', numberLength: 10 },
  { name: 'Armenia', code: '374', prefix: '374', numberLength: 8 },
  { name: 'Aruba', code: '297', prefix: '297', numberLength: 7 },
  { name: 'Australia', code: '61', prefix: '61', numberLength: 10 },
  { name: 'Austria', code: '43', prefix: '43', numberLength: 10 },
  { name: 'Azerbaijan', code: '994', prefix: '994', numberLength: 10 },
  { name: 'Bahamas', code: '1', prefix: '1', numberLength: 10 },
  { name: 'Bahrain', code: '973', prefix: '973', numberLength: 8 },
  { name: 'Bangladesh', code: '880', prefix: '880', numberLength: 11 },
  { name: 'Barbados', code: '1', prefix: '1', numberLength: 10 },
  { name: 'Belarus', code: '375', prefix: '375', numberLength: 9 },
  { name: 'Belgium', code: '32', prefix: '32', numberLength: 10 },
  { name: 'Belize', code: '501', prefix: '501', numberLength: 7 },
  { name: 'Benin', code: '229', prefix: '229', numberLength: 8 },
  { name: 'Bermuda', code: '1', prefix: '1', numberLength: 10 },
  { name: 'Bhutan', code: '975', prefix: '975', numberLength: 8 },
  { name: 'Bolivia', code: '591', prefix: '591', numberLength: 8 },
  {
    name: 'Bosnia and Herzegovina',
    code: '387',
    prefix: '387',
    numberLength: 8
  },
  { name: 'Botswana', code: '267', prefix: '267', numberLength: 10 },
  { name: 'Brazil', code: '55', prefix: '55', numberLength: 11 },
  { name: 'Brunei', code: '673', prefix: '673', numberLength: 8 },
  { name: 'Bulgaria', code: '359', prefix: '359', numberLength: 10 },
  { name: 'Burkina Faso', code: '226', prefix: '226', numberLength: 10 },
  { name: 'Burundi', code: '257', prefix: '257', numberLength: 10 },
  { name: 'Cambodia', code: '855', prefix: '855', numberLength: 10 },
  { name: 'Cameroon', code: '237', prefix: '237', numberLength: 10 },
  { name: 'Canada', code: '1', prefix: '1', numberLength: 10 },
  { name: 'Cape Verde', code: '238', prefix: '238', numberLength: 9 },
  { name: 'Cayman Islands', code: '1', prefix: '1', numberLength: 10 },
  {
    name: 'Central African Republic',
    code: '236',
    prefix: '236',
    numberLength: 8
  },
  { name: 'Chad', code: '235', prefix: '235', numberLength: 10 },
  { name: 'Chile', code: '56', prefix: '56', numberLength: 9 },
  { name: 'China', code: '86', prefix: '86', numberLength: 11 },
  { name: 'Colombia', code: '57', prefix: '57', numberLength: 10 },
  { name: 'Comoros', code: '269', prefix: '269', numberLength: 8 },
  { name: 'Congo', code: '242', prefix: '242', numberLength: 9 },
  {
    name: 'Congo, Democratic Republic of the',
    code: '243',
    prefix: '243',
    numberLength: 9
  },
  { name: 'Cook Islands', code: '682', prefix: '682', numberLength: 8 },
  { name: 'Costa Rica', code: '506', prefix: '506', numberLength: 8 },
  { name: "Côte d'Ivoire", code: '225', prefix: '225', numberLength: 10 },
  { name: 'Croatia', code: '385', prefix: '385', numberLength: 9 },
  { name: 'Cuba', code: '53', prefix: '53', numberLength: 8 },
  { name: 'Cyprus', code: '357', prefix: '357', numberLength: 8 },
  { name: 'Czech Republic', code: '420', prefix: '420', numberLength: 9 },
  { name: 'Denmark', code: '45', prefix: '45', numberLength: 8 },
  { name: 'Djibouti', code: '253', prefix: '253', numberLength: 10 },
  { name: 'Dominica', code: '1', prefix: '1', numberLength: 10 },
  { name: 'Dominican Republic', code: '1', prefix: '1', numberLength: 10 },
  { name: 'Ecuador', code: '593', prefix: '593', numberLength: 9 },
  { name: 'Egypt', code: '20', prefix: '20', numberLength: 11 },
  { name: 'El Salvador', code: '503', prefix: '503', numberLength: 8 },
  { name: 'Equatorial Guinea', code: '240', prefix: '240', numberLength: 9 },
  { name: 'Eritrea', code: '293', prefix: '293', numberLength: 10 },
  { name: 'Estonia', code: '372', prefix: '372', numberLength: 8 },
  { name: 'Eswatini', code: '268', prefix: '268', numberLength: 10 },
  { name: 'Ethiopia', code: '251', prefix: '251', numberLength: 10 },
  { name: 'Fiji', code: '679', prefix: '679', numberLength: 8 },
  { name: 'Finland', code: '358', prefix: '358', numberLength: 9 },
  { name: 'France', code: '33', prefix: '33', numberLength: 10 },
  { name: 'French Guiana', code: '594', prefix: '594', numberLength: 10 },
  { name: 'French Polynesia', code: '689', prefix: '689', numberLength: 8 },
  { name: 'Gabon', code: '241', prefix: '241', numberLength: 9 },
  { name: 'Gambia', code: '220', prefix: '220', numberLength: 7 },
  { name: 'Georgia', code: '995', prefix: '995', numberLength: 9 },
  { name: 'Germany', code: '49', prefix: '49', numberLength: 11 },
  { name: 'Ghana', code: '233', prefix: '233', numberLength: 10 },
  { name: 'Gibraltar', code: '350', prefix: '350', numberLength: 8 },
  { name: 'Greece', code: '30', prefix: '30', numberLength: 10 },
  { name: 'Grenada', code: '1', prefix: '1', numberLength: 10 },
  { name: 'Guadeloupe', code: '590', prefix: '590', numberLength: 10 },
  { name: 'Guatemala', code: '502', prefix: '502', numberLength: 8 },
  { name: 'Guinea', code: '224', prefix: '224', numberLength: 10 },
  { name: 'Guinea-Bissau', code: '245', prefix: '245', numberLength: 9 },
  { name: 'Guyana', code: '592', prefix: '592', numberLength: 7 },
  { name: 'Haiti', code: '509', prefix: '509', numberLength: 10 },
  { name: 'Honduras', code: '504', prefix: '504', numberLength: 8 },
  { name: 'Hungary', code: '36', prefix: '36', numberLength: 10 },
  { name: 'Iceland', code: '354', prefix: '354', numberLength: 8 },
  { name: 'India', code: '91', prefix: '91', numberLength: 10 },
  { name: 'Indonesia', code: '62', prefix: '62', numberLength: 10 },
  { name: 'Iran', code: '98', prefix: '98', numberLength: 11 },
  { name: 'Iraq', code: '964', prefix: '964', numberLength: 11 },
  { name: 'Ireland', code: '353', prefix: '353', numberLength: 10 },
  { name: 'Israel', code: '972', prefix: '972', numberLength: 10 },
  { name: 'Italy', code: '39', prefix: '39', numberLength: 10 },
  { name: 'Jamaica', code: '1', prefix: '1', numberLength: 10 },
  { name: 'Japan', code: '81', prefix: '81', numberLength: 11 },
  { name: 'Jordan', code: '962', prefix: '962', numberLength: 10 },
  { name: 'Kazakhstan', code: '7', prefix: '7', numberLength: 11 },
  { name: 'Kenya', code: '254', prefix: '254', numberLength: 10 },
  { name: 'Kiribati', code: '686', prefix: '686', numberLength: 8 },
  { name: 'Kuwait', code: '965', prefix: '965', numberLength: 8 },
  { name: 'Kyrgyzstan', code: '996', prefix: '996', numberLength: 10 },
  { name: 'Laos', code: '856', prefix: '856', numberLength: 10 },
  { name: 'Latvia', code: '371', prefix: '371', numberLength: 8 },
  { name: 'Lebanon', code: '961', prefix: '961', numberLength: 10 },
  { name: 'Lesotho', code: '266', prefix: '266', numberLength: 10 },
  { name: 'Liberia', code: '231', prefix: '231', numberLength: 10 },
  { name: 'Libya', code: '218', prefix: '218', numberLength: 10 },
  { name: 'Liechtenstein', code: '423', prefix: '423', numberLength: 8 },
  { name: 'Lithuania', code: '370', prefix: '370', numberLength: 8 },
  { name: 'Luxembourg', code: '352', prefix: '352', numberLength: 8 },
  { name: 'Madagascar', code: '261', prefix: '261', numberLength: 10 },
  { name: 'Malawi', code: '265', prefix: '265', numberLength: 10 },
  { name: 'Malaysia', code: '60', prefix: '60', numberLength: 10 },
  { name: 'Maldives', code: '960', prefix: '960', numberLength: 9 },
  { name: 'Mali', code: '223', prefix: '223', numberLength: 8 },
  { name: 'Malta', code: '356', prefix: '356', numberLength: 8 },
  { name: 'Marshall Islands', code: '692', prefix: '692', numberLength: 8 },
  { name: 'Martinique', code: '596', prefix: '596', numberLength: 10 },
  { name: 'Mauritania', code: '222', prefix: '222', numberLength: 10 },
  { name: 'Mauritius', code: '230', prefix: '230', numberLength: 9 },
  { name: 'Mexico', code: '52', prefix: '52', numberLength: 10 },
  { name: 'Micronesia', code: '691', prefix: '691', numberLength: 8 },
  { name: 'Moldova', code: '373', prefix: '373', numberLength: 10 },
  { name: 'Monaco', code: '377', prefix: '377', numberLength: 8 },
  { name: 'Mongolia', code: '976', prefix: '976', numberLength: 8 },
  { name: 'Montenegro', code: '382', prefix: '382', numberLength: 8 },
  { name: 'Montserrat', code: '1', prefix: '1', numberLength: 10 },
  { name: 'Morocco', code: '212', prefix: '212', numberLength: 10 },
  { name: 'Mozambique', code: '258', prefix: '258', numberLength: 10 },
  { name: 'Myanmar', code: '95', prefix: '95', numberLength: 10 },
  { name: 'Namibia', code: '264', prefix: '264', numberLength: 10 },
  { name: 'Nauru', code: '674', prefix: '674', numberLength: 8 },
  { name: 'Nepal', code: '977', prefix: '977', numberLength: 10 },
  { name: 'Netherlands', code: '31', prefix: '31', numberLength: 10 },
  { name: 'Netherlands Antilles', code: '599', prefix: '599', numberLength: 7 },
  { name: 'New Caledonia', code: '687', prefix: '687', numberLength: 8 },
  { name: 'New Zealand', code: '64', prefix: '64', numberLength: 10 },
  { name: 'Nicaragua', code: '505', prefix: '505', numberLength: 8 },
  { name: 'Niger', code: '227', prefix: '227', numberLength: 10 },
  { name: 'Nigeria', code: '234', prefix: '234', numberLength: 11 },
  { name: 'Niue', code: '683', prefix: '683', numberLength: 4 },
  { name: 'Norfolk Island', code: '672', prefix: '672', numberLength: 8 },
  {
    name: 'Northern Mariana Islands',
    code: '1',
    prefix: '1',
    numberLength: 10
  },
  { name: 'Norway', code: '47', prefix: '47', numberLength: 8 },
  { name: 'Oman', code: '968', prefix: '968', numberLength: 8 },
  { name: 'Pakistan', code: '92', prefix: '92', numberLength: 11 },
  { name: 'Palau', code: '680', prefix: '680', numberLength: 8 },
  { name: 'Palestine, State of', code: '970', prefix: '970', numberLength: 10 },
  { name: 'Panama', code: '507', prefix: '507', numberLength: 8 },
  { name: 'Papua New Guinea', code: '675', prefix: '675', numberLength: 8 },
  { name: 'Paraguay', code: '595', prefix: '595', numberLength: 10 },
  { name: 'Peru', code: '51', prefix: '51', numberLength: 9 },
  { name: 'Philippines', code: '63', prefix: '63', numberLength: 11 },
  { name: 'Poland', code: '48', prefix: '48', numberLength: 9 },
  { name: 'Portugal', code: '351', prefix: '351', numberLength: 9 },
  { name: 'Qatar', code: '974', prefix: '974', numberLength: 8 },
  { name: 'Romania', code: '40', prefix: '40', numberLength: 10 },
  { name: 'Russia', code: '7', prefix: '7', numberLength: 11 },
  { name: 'Rwanda', code: '250', prefix: '250', numberLength: 10 },
  { name: 'Saint Kitts and Nevis', code: '1', prefix: '1', numberLength: 10 },
  { name: 'Saint Lucia', code: '1', prefix: '1', numberLength: 10 },
  {
    name: 'Saint Vincent and the Grenadines',
    code: '1',
    prefix: '1',
    numberLength: 10
  },
  { name: 'Samoa', code: '685', prefix: '685', numberLength: 8 },
  { name: 'San Marino', code: '378', prefix: '378', numberLength: 8 },
  {
    name: 'Sao Tome and Principe',
    code: '239',
    prefix: '239',
    numberLength: 9
  },
  { name: 'Saudi Arabia', code: '966', prefix: '966', numberLength: 11 },
  { name: 'Senegal', code: '221', prefix: '221', numberLength: 10 },
  { name: 'Serbia', code: '381', prefix: '381', numberLength: 10 },
  { name: 'Seychelles', code: '248', prefix: '248', numberLength: 7 },
  { name: 'Sierra Leone', code: '232', prefix: '232', numberLength: 10 },
  { name: 'Singapore', code: '65', prefix: '65', numberLength: 8 },
  { name: 'Slovakia', code: '421', prefix: '421', numberLength: 10 },
  { name: 'Slovenia', code: '386', prefix: '386', numberLength: 9 },
  { name: 'Solomon Islands', code: '677', prefix: '677', numberLength: 8 },
  { name: 'Somalia', code: '252', prefix: '252', numberLength: 10 },
  { name: 'South Africa', code: '27', prefix: '27', numberLength: 10 },
  { name: 'South Sudan', code: '211', prefix: '211', numberLength: 10 },
  { name: 'Spain', code: '34', prefix: '34', numberLength: 9 },
  { name: 'Sri Lanka', code: '94', prefix: '94', numberLength: 10 },
  { name: 'Sudan', code: '249', prefix: '249', numberLength: 10 },
  { name: 'Suriname', code: '597', prefix: '597', numberLength: 7 },
  { name: 'Sweden', code: '46', prefix: '46', numberLength: 10 },
  { name: 'Switzerland', code: '41', prefix: '41', numberLength: 10 },
  { name: 'Syria', code: '963', prefix: '963', numberLength: 10 },
  { name: 'Taiwan', code: '886', prefix: '886', numberLength: 10 },
  { name: 'Tajikistan', code: '992', prefix: '992', numberLength: 10 },
  { name: 'Tanzania', code: '255', prefix: '255', numberLength: 10 },
  { name: 'Thailand', code: '66', prefix: '66', numberLength: 10 },
  { name: 'Timor-Leste', code: '670', prefix: '670', numberLength: 10 },
  { name: 'Togo', code: '228', prefix: '228', numberLength: 10 },
  { name: 'Tonga', code: '676', prefix: '676', numberLength: 8 },
  { name: 'Trinidad and Tobago', code: '1', prefix: '1', numberLength: 10 },
  { name: 'Tunisia', code: '216', prefix: '216', numberLength: 10 },
  { name: 'Turkey', code: '90', prefix: '90', numberLength: 11 },
  { name: 'Turkmenistan', code: '993', prefix: '993', numberLength: 10 },
  {
    name: 'Turks and Caicos Islands',
    code: '1',
    prefix: '1',
    numberLength: 10
  },
  { name: 'Tuvalu', code: '688', prefix: '688', numberLength: 8 },
  { name: 'Uganda', code: '256', prefix: '256', numberLength: 10 },
  { name: 'Ukraine', code: '380', prefix: '380', numberLength: 10 },
  {
    name: 'United Arab Emirates',
    code: '971',
    prefix: '971',
    numberLength: 10
  },
  { name: 'United Kingdom', code: '44', prefix: '44', numberLength: 11 },
  { name: 'United States', code: '1', prefix: '1', numberLength: 10 },
  { name: 'Uruguay', code: '598', prefix: '598', numberLength: 9 },
  { name: 'Uzbekistan', code: '998', prefix: '998', numberLength: 10 },
  { name: 'Vanuatu', code: '678', prefix: '678', numberLength: 8 },
  { name: 'Vatican', code: '379', prefix: '379', numberLength: 8 },
  { name: 'Venezuela', code: '58', prefix: '58', numberLength: 11 },
  { name: 'Vietnam', code: '84', prefix: '84', numberLength: 10 },
  { name: 'Virgin Islands, British', code: '1', prefix: '1', numberLength: 10 },
  { name: 'Virgin Islands, U.S.', code: '1', prefix: '1', numberLength: 10 },
  { name: 'Wallis and Futuna', code: '681', prefix: '681', numberLength: 8 },
  { name: 'Yemen', code: '967', prefix: '967', numberLength: 10 },
  { name: 'Zambia', code: '260', prefix: '260', numberLength: 10 },
  { name: 'Zimbabwe', code: '263', prefix: '263', numberLength: 10 }
];
